### read all users
GET http://localhost:4000/user-api/users


### read user by ObjectID
GET http://localhost:4000/user-api/users/69809b9173188e63f3b420aa

### create users
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"priya",
    "password":"gamya",
    "age":20
}


### update users
PUT http://localhost:4000/user-api/users/69809b9173188e63f3b420aa
Content-Type: application/json

{
    "username":"priya",
    "password":"gamya",
    "age":15    
}



### delete  user by ObjectID
DELETE http://localhost:4000/user-api/users/69809b9173188e63f3b420aa


### user authentication(Login) req
POST  http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "username":"priya",
    "password":"gamya"
}


### req for protected route
GET http://localhost:4000/user-api/test





#############################

### read all products
GET http://localhost:4000/product-api/products

### read product by ObjectID
GET http://localhost:4000/product-api/products/69809b5373188e63f3b420a3


### create product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "pid":"100",
    "productName":"samsung",
    "price":100000
}


### update product by ObjectID
PUT http://localhost:4000/product-api/products/69809b5373188e63f3b420a3
Content-Type: application/json

{
    "pid":"100",
    "productName":"iphone",
    "price":100000
}


