GET http://127.0.0.1:3000/user-api/users

###

POST http://127.0.0.1:3000/user-api/users
Content-Type: application/json

{
    "id":100,
    "name":"ram",
    "age":19
}

###

PUT http://127.0.0.1:3000/user-api/users
Content-Type: application/json

{
    "id":100,
    "name":"ram",
    "age":21
}

###

GET http://127.0.0.1:3000/user-api/users/100

###

DELETE http://127.0.0.1:3000/user-api/users/100


###
GET http://127.0.0.1:3000/product-api/products

###
GET http://127.0.0.1:3000/product-api/products/100

###
GET  http://127.0.0.1:3000/product-api/products-brand/hp


###
POST http://127.0.0.1:3000/product-api/products
Content-Type: application/json

{
    "productId":100,
    "name":"laptop",
    "price":100000,
    "brand":"hp"
}


###

PUT http://127.0.0.1:3000/product-api/products
Content-Type: application/json

{
    "productId":200,
    "name":"laptop",
    "price":100000,
    "brand":"dell"
}



###

DELETE http://127.0.0.1:3000/product-api/products/200